# Generated by Django 5.2.4 on 2025-08-14 22:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=84)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('floor', models.IntegerField()),
                ('idicatedLimit', models.IntegerField()),
                ('fkBuilding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_building', to='rooms.building')),
            ],
        ),
    ]
