# Generated by Django 5.2.4 on 2025-08-14 22:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entryTime', models.TimeField()),
                ('exitTime', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dtReserve', models.DateField()),
                ('status', models.IntegerField(choices=[(0, 'Reservado'), (1, 'Cancelado'), (2, 'Concluído')])),
                ('fkRoom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserve_room', to='rooms.room')),
                ('fkUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserver_owner', to=settings.AUTH_USER_MODEL)),
                ('schedules', models.ManyToManyField(related_name='reserve_schedules', to='reservation.schedule')),
            ],
        ),
    ]
